/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('public_places').insert([
    {id: 0, name: 'RUA'},
    {id: 1, name: 'AEROPORTO'},
    {id: 2, name: 'ALAMEDA'},
    {id: 3, name: 'ÁREA'},
    {id: 4, name: 'AVENIDA'},
    {id: 5, name: 'CAMPO'},
    {id: 6, name: 'CHÁCARA'},
    {id: 7, name: 'COLÔNIA'},
    {id: 8, name: 'CONDOMÍNIO'},
    {id: 9, name: 'CONJUNTO'},
    {id: 10, name: 'DISTRITO'},
    {id: 11, name: 'ESPLANADA'},
    {id: 12, name: 'ESTAÇÃO'},
    {id: 13, name: 'ESTRADA'},
    {id: 14, name: 'FAVELA'},
    {id: 15, name: 'FAZENDA'},
    {id: 16, name: 'FEIRA'},
    {id: 17, name: 'JARDIM'},
    {id: 18, name: 'LADEIRA'},
    {id: 19, name: 'LAGO'},
    {id: 20, name: 'LAGOA'},
    {id: 21, name: 'LARGO'},
    {id: 22, name: 'LOTEAMENTO'},
    {id: 23, name: 'MORRO'},
    {id: 24, name: 'NÚCLEO'},
    {id: 25, name: 'PARQUE'},
    {id: 26, name: 'PASSARELA'},
    {id: 27, name: 'PÁTIO'},
    {id: 28, name: 'PRAÇA'},
    {id: 29, name: 'QUADRA'},
    {id: 30, name: 'RECANTO'},
    {id: 31, name: 'RESIDENCIAL'},
    {id: 32, name: 'RODOVIA'},
    {id: 33, name: 'SERVIDÃO'},
    {id: 34, name: 'SETOR'},
    {id: 35, name: 'SÍTIO'},
    {id: 36, name: 'TRAVESSA'},
    {id: 37, name: 'TRECHO'},
    {id: 38, name: 'TREVO'},
    {id: 39, name: 'VALE'},
    {id: 40, name: 'VEREDA'},
    {id: 41, name: 'VIA'},
    {id: 42, name: 'VIADUTO'},
    {id: 43, name: 'VIELA'},
    {id: 44, name: 'VILA'},
  ]);
};
